name: CI

on: pull_request

permissions:
  contents: read
  pull-requests: write

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests with Coverage
        run: |
          pytest -n auto \
            --cov=note_api \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-report=html \
            --junitxml=pytest.xml \
            --cov-fail-under=80 \
            tests/

      - name: Check Coverage Threshold
        if: ${{ failure() }}
        run: |
          echo "::error::Coverage is below the required threshold of 80%"
          exit 1

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}

  # The check is implemented on the Snyk side
  # because for some reason it fails to authenticate
  # when running in the repo of a Github Org.
  # This could be because Orgs should authenticate via Service Account
  # (see https://docs.snyk.io/snyk-cli/authenticate-to-use-the-cli#how-to-authenticate-to-use-the-cli-in-ci-cd-pipelines).
  # However the Snyk docu does not document this behaviour.
  # TL;DL: Snyks PATs are not working in a Github Org Repos.
  #
  # snyk:
  #   name: Snyk
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/python@master
  #       continue-on-error: true
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #         args: --sarif-file-output=snyk.sarif

  #     - name: Upload result to GitHub Code Scanning
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: snyk.sarif